export type ElementInfo = { Z: number; symbol: string; name: string };

// Minimal dataset (1-100) for display purposes. Extend as needed.
export const PERIODIC_TABLE: Record<number, ElementInfo> = {
  1: { Z: 1, symbol: "H", name: "Hydrogen" },
  2: { Z: 2, symbol: "He", name: "Helium" },
  3: { Z: 3, symbol: "Li", name: "Lithium" },
  4: { Z: 4, symbol: "Be", name: "Beryllium" },
  5: { Z: 5, symbol: "B", name: "Boron" },
  6: { Z: 6, symbol: "C", name: "Carbon" },
  7: { Z: 7, symbol: "N", name: "Nitrogen" },
  8: { Z: 8, symbol: "O", name: "Oxygen" },
  9: { Z: 9, symbol: "F", name: "Fluorine" },
  10: { Z: 10, symbol: "Ne", name: "Neon" },
  11: { Z: 11, symbol: "Na", name: "Sodium" },
  12: { Z: 12, symbol: "Mg", name: "Magnesium" },
  13: { Z: 13, symbol: "Al", name: "Aluminium" },
  14: { Z: 14, symbol: "Si", name: "Silicon" },
  15: { Z: 15, symbol: "P", name: "Phosphorus" },
  16: { Z: 16, symbol: "S", name: "Sulfur" },
  17: { Z: 17, symbol: "Cl", name: "Chlorine" },
  18: { Z: 18, symbol: "Ar", name: "Argon" },
  19: { Z: 19, symbol: "K", name: "Potassium" },
  20: { Z: 20, symbol: "Ca", name: "Calcium" },
  21: { Z: 21, symbol: "Sc", name: "Scandium" },
  22: { Z: 22, symbol: "Ti", name: "Titanium" },
  23: { Z: 23, symbol: "V", name: "Vanadium" },
  24: { Z: 24, symbol: "Cr", name: "Chromium" },
  25: { Z: 25, symbol: "Mn", name: "Manganese" },
  26: { Z: 26, symbol: "Fe", name: "Iron" },
  27: { Z: 27, symbol: "Co", name: "Cobalt" },
  28: { Z: 28, symbol: "Ni", name: "Nickel" },
  29: { Z: 29, symbol: "Cu", name: "Copper" },
  30: { Z: 30, symbol: "Zn", name: "Zinc" },
  31: { Z: 31, symbol: "Ga", name: "Gallium" },
  32: { Z: 32, symbol: "Ge", name: "Germanium" },
  33: { Z: 33, symbol: "As", name: "Arsenic" },
  34: { Z: 34, symbol: "Se", name: "Selenium" },
  35: { Z: 35, symbol: "Br", name: "Bromine" },
  36: { Z: 36, symbol: "Kr", name: "Krypton" },
  37: { Z: 37, symbol: "Rb", name: "Rubidium" },
  38: { Z: 38, symbol: "Sr", name: "Strontium" },
  39: { Z: 39, symbol: "Y", name: "Yttrium" },
  40: { Z: 40, symbol: "Zr", name: "Zirconium" },
  41: { Z: 41, symbol: "Nb", name: "Niobium" },
  42: { Z: 42, symbol: "Mo", name: "Molybdenum" },
  43: { Z: 43, symbol: "Tc", name: "Technetium" },
  44: { Z: 44, symbol: "Ru", name: "Ruthenium" },
  45: { Z: 45, symbol: "Rh", name: "Rhodium" },
  46: { Z: 46, symbol: "Pd", name: "Palladium" },
  47: { Z: 47, symbol: "Ag", name: "Silver" },
  48: { Z: 48, symbol: "Cd", name: "Cadmium" },
  49: { Z: 49, symbol: "In", name: "Indium" },
  50: { Z: 50, symbol: "Sn", name: "Tin" },
  51: { Z: 51, symbol: "Sb", name: "Antimony" },
  52: { Z: 52, symbol: "Te", name: "Tellurium" },
  53: { Z: 53, symbol: "I", name: "Iodine" },
  54: { Z: 54, symbol: "Xe", name: "Xenon" },
  55: { Z: 55, symbol: "Cs", name: "Cesium" },
  56: { Z: 56, symbol: "Ba", name: "Barium" },
  57: { Z: 57, symbol: "La", name: "Lanthanum" },
  58: { Z: 58, symbol: "Ce", name: "Cerium" },
  59: { Z: 59, symbol: "Pr", name: "Praseodymium" },
  60: { Z: 60, symbol: "Nd", name: "Neodymium" },
  61: { Z: 61, symbol: "Pm", name: "Promethium" },
  62: { Z: 62, symbol: "Sm", name: "Samarium" },
  63: { Z: 63, symbol: "Eu", name: "Europium" },
  64: { Z: 64, symbol: "Gd", name: "Gadolinium" },
  65: { Z: 65, symbol: "Tb", name: "Terbium" },
  66: { Z: 66, symbol: "Dy", name: "Dysprosium" },
  67: { Z: 67, symbol: "Ho", name: "Holmium" },
  68: { Z: 68, symbol: "Er", name: "Erbium" },
  69: { Z: 69, symbol: "Tm", name: "Thulium" },
  70: { Z: 70, symbol: "Yb", name: "Ytterbium" },
  71: { Z: 71, symbol: "Lu", name: "Lutetium" },
  72: { Z: 72, symbol: "Hf", name: "Hafnium" },
  73: { Z: 73, symbol: "Ta", name: "Tantalum" },
  74: { Z: 74, symbol: "W", name: "Tungsten" },
  75: { Z: 75, symbol: "Re", name: "Rhenium" },
  76: { Z: 76, symbol: "Os", name: "Osmium" },
  77: { Z: 77, symbol: "Ir", name: "Iridium" },
  78: { Z: 78, symbol: "Pt", name: "Platinum" },
  79: { Z: 79, symbol: "Au", name: "Gold" },
  80: { Z: 80, symbol: "Hg", name: "Mercury" },
  81: { Z: 81, symbol: "Tl", name: "Thallium" },
  82: { Z: 82, symbol: "Pb", name: "Lead" },
  83: { Z: 83, symbol: "Bi", name: "Bismuth" },
  84: { Z: 84, symbol: "Po", name: "Polonium" },
  85: { Z: 85, symbol: "At", name: "Astatine" },
  86: { Z: 86, symbol: "Rn", name: "Radon" },
  87: { Z: 87, symbol: "Fr", name: "Francium" },
  88: { Z: 88, symbol: "Ra", name: "Radium" },
  89: { Z: 89, symbol: "Ac", name: "Actinium" },
  90: { Z: 90, symbol: "Th", name: "Thorium" },
  91: { Z: 91, symbol: "Pa", name: "Protactinium" },
  92: { Z: 92, symbol: "U", name: "Uranium" },
  93: { Z: 93, symbol: "Np", name: "Neptunium" },
  94: { Z: 94, symbol: "Pu", name: "Plutonium" },
  95: { Z: 95, symbol: "Am", name: "Americium" },
  96: { Z: 96, symbol: "Cm", name: "Curium" },
  97: { Z: 97, symbol: "Bk", name: "Berkelium" },
  98: { Z: 98, symbol: "Cf", name: "Californium" },
  99: { Z: 99, symbol: "Es", name: "Einsteinium" },
  100: { Z: 100, symbol: "Fm", name: "Fermium" },
};

export function getElementInfo(Z: number): ElementInfo | undefined {
  return PERIODIC_TABLE[Z];
}


